### ISSUE TITLE
Add support for HTTP Basic Authentication

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-auth#5]
### What is the idea?

Add support for a using HTTP Basic Authentication via the conda-auth plugin.

### Why is this needed?

This will be one of the primary types of authentication that we initially support with this plugin.

### What should happen?

- [ ] Review current implementation (see main branch) and improve where necessary
  - [ ] We need better test coverage (focus on unit tests with mocks for now)
  - [ ] Error handling for failed login attempts can be improved
- [ ] Add `--username` and `--password` CLI options 
- [ ] Add documentation for how to configure this type of authentication to our documentation website

**Comment by beeankha** [comment]
A few thoughts/questions that may be good to consider for an implementation of HTTP Basic Auth support:
1. When logging in or out, there should be output that indicates to the user whether the login/logout command was successful (along with a warning/error when there's an unsuccessful login attempt). If there's no output with a login (whether successful or not), the user might think "There's no output so I'm successfully logged in!" but when they try to do something with the channel later they'll get an error and may not immediately realize why.
2. When attempting to log in again after having logged in previously, perhaps there should be a message that says "You are already logged in to this channel"?
3. Will there be a [retry limit](https://requests.readthedocs.io/en/latest/user/advanced/#example-automatic-retries) enforced for failed login attempts?
4. If possible, specific error cases (not just for HTTP Basic Auth, but for each kind of authentication method) should output a helpful message like the `CondaAuthError` below:
```
CondaAuthError: Unrecognized channel: default. Make sure this channel is defined in your conda configuration and has an entry in "channel_settings".

channel_settings:
  - channel: default
    auth: conda-auth-basic-auth
    username: user_one
```
Error messages like the above list out exactly how to fix the problem and reduce the amount of trial and error that the auth plugin user has to go through, which makes for great UX. 👍
